# Generated by Django 3.2.9 on 2022-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unp',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
