# Generated by Django 3.2.9 on 2022-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0003_profile_unp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='preview_image',
            field=models.ImageField(default='grey.jpg', upload_to='preview_images'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='short_description',
            field=models.TextField(default='', max_length=625),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(related_name='restaurant', to='otzovik_app.RestaurantCuisine'),
        ),
    ]
