# Generated by Django 3.2.9 on 2022-08-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0004_auto_20220823_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.profile'),
        ),
    ]
