# Generated by Django 3.2.9 on 2022-08-24 14:12

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0007_alter_restaurant_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='preview_image',
        ),
        migrations.CreateModel(
            name='PreviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', django_resized.forms.ResizedImageField(crop=None, default='grey.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[640, 360], upload_to='preview_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant')),
            ],
        ),
    ]
