# Generated by Django 3.2.9 on 2022-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0008_auto_20220824_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewimage',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
