# Generated by Django 3.2.9 on 2022-08-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0009_previewimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant'),
        ),
    ]
