# Generated by Django 3.2.9 on 2022-08-24 14:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0012_remove_previewimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewimage',
            name='preview_image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='grey.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[640, 360], upload_to='preview_images'),
        ),
    ]
