# Generated by Django 3.2.9 on 2022-08-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0013_alter_previewimage_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='addressforgoogle',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant'),
        ),
    ]
