# Generated by Django 3.2.9 on 2022-08-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0014_auto_20220826_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quality', models.IntegerField(default=1)),
                ('staff_quality', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=1, null=True)),
                ('body', models.TextField(max_length=1000)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otzovik_app.profile')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant')),
            ],
        ),
    ]
