# Generated by Django 3.2.9 on 2022-08-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0015_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_quality', models.FloatField(default=0)),
                ('staff_quality', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('restaurant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant')),
            ],
        ),
    ]
