# Generated by Django 3.2.9 on 2022-09-12 12:38

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0019_alter_review_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(limit_choices_to=3, related_name='restaurant', to='otzovik_app.RestaurantCuisine'),
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='grey.jpg', force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='restaurant_images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant')),
            ],
        ),
    ]
