# Generated by Django 3.2.9 on 2022-09-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0020_auto_20220912_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(limit_choices_to=15, related_name='restaurant', to='otzovik_app.RestaurantCuisine'),
        ),
    ]
