# Generated by Django 3.2.9 on 2022-09-16 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0022_alter_restaurant_cuisines'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCuisineStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurantcuisine')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.profile')),
            ],
        ),
    ]
