# Generated by Django 4.1.3 on 2022-12-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0024_admin'),
    ]

    operations = [
        migrations.RenameModel('AddressForGoogle', 'Coordinates')
    ]
