# Generated by Django 4.1.3 on 2023-02-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0025_auto_20221222_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='profile',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.coordinates'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.profile'),
        ),
        migrations.AlterField(
            model_name='profilecuisinestatistics',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.profile'),
        ),
        migrations.AlterField(
            model_name='reviewsummary',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.restaurant'),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('nip', models.CharField(max_length=20)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.address')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otzovik_app.companyprofile'),
        ),
    ]
