# Generated by Django 4.1.3 on 2023-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0026_remove_address_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='owner_name',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='owner_surname',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
