# Generated by Django 4.1.3 on 2023-02-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0027_companyprofile_owner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='company',
            new_name='company_profile',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='otzovik_app.profile'),
        ),
    ]
