# Generated by Django 4.1 on 2023-05-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0029_city_remove_address_city_address_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_name',
            new_name='city',
        ),
    ]
