# Generated by Django 4.1 on 2023-05-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otzovik_app', '0032_profile_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='otzovik_app.restaurantfoodtype'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant', to='otzovik_app.restaurantprice'),
        ),
    ]
